source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "FreestarBannerApp" do
    pod 'FSAdSDK/Banner'
    pod 'FSAdSDK/Mediation/MoPub'
    pod 'FSAdSDK/Mediation/Facebook'
    pod 'Google-Mobile-Ads-SDK', '7.50.0'
end
