source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "FreestarBannerApp" do
    pod 'FSAdSDK/Banner'    
    pod 'PrebidMobileFS'
    pod 'Google-Mobile-Ads-SDK', '~> 7.24.1'
end
