source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "FreestarBannerApp" do
    pod 'FSAdSDK/Banner'
    pod 'Google-Mobile-Ads-SDK', :git => 'https://github.com/maddapper/GMA-iOS-SDK.git', '~> 7.41.0'
end
