source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "FreestarInterstitialApp" do
    pod 'FSAdSDK/Interstitial'
    pod 'FSAdSDK/Mediation/MoPub'
    pod 'Google-Mobile-Ads-SDK', :git => 'https://github.com/freestarcapital/GMA-iOS-SDK.git', :tag => '7.50.0'
end
