source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "FreestarInterstitialApp" do
    pod 'FSAdSDK/Banner'  // Freestar Ad SDK
    pod 'FSAdSDK/Mediation/MoPub'
    pod 'Google-Mobile-Ads-SDK', '7.50.0'  // Primary Ad SDK
end
